#=================================================================
# log 日志
#=================================================================
server:
  port: 8080 # 项目运行端口，默认 8080
logging:
  config: classpath:logback-wayblog.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/wayblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Wayblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://39.105.193.69:9000
  accessKey: way
  secretKey: weihang1008
  bucketName: wayblog
